server:
  port: 8090
telegram:
  bot:
    credentials:
      token: 6012426436:AAFXQNLCrLfUW3c1Z1sTzdXcD1zxpQ80h5M
      bot-username: Cp_HuntyBot
spring:
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/HuntyDb?authSource=admin
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG


